# Generated by Django 4.2.2 on 2023-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.CharField(max_length=500)),
                ('second_choice', models.CharField(max_length=500)),
                ('third_choice', models.CharField(max_length=500)),
                ('fourth_choice', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
